-- AlterTable
ALTER TABLE `comments` MODIFY `likes` INTEGER NOT NULL DEFAULT 0,
    MODIFY `deslike` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `posts` MODIFY `likes` INTEGER NOT NULL DEFAULT 0,
    MODIFY `deslike` INTEGER NOT NULL DEFAULT 0;
